version: '3.8'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PASS} #root
    ports:
      - '3306:3306'
    volumes:
      - type: "bind"
        source: "${WORKING_DIR}/data"
        target: "/var/lib/mysql"